BOSS_QUESTIONS = [
    "How well is my entire team working?",
    "Which employees consistently meet deadlines?",
    "Who frequently asks for deadline extensions?",
    "Which team members need constant supervision?",
    "Who takes initiative without being reminded?",
    "Who requires multiple revisions for tasks?",
    "Are some employees avoiding challenging tasks?",
    "Who tends to overcommit or underdeliver?",
    "Who seems most motivated at work?",
    "Which employees look disengaged?",
    "Which employees are high-risk for task failure?",
    "Who can handle complex, critical tasks?",
    "Who needs immediate performance improvement?",
    "Who are my top employees?",
    "Are we finishing work on time?",
    "Where are we facing problems?",
    "Which team is doing great work?",
    "Who completes tasks fastest?",
    "Which team needs more help?",
    "How long do tasks usually take?",
    "Are some tasks taking too much time?",
    "Can I see everyone's work progress?",
    "Which departments are most/least efficient?",
    "What is the company-wide task completion rate?",
    "Who are the top 3 performers in the organization?",
    "What is the average task completion time?",
    "How many critical tasks are pending?",
    "Which managers are most effective in task delegation?",
    "Which teams need immediate intervention?",
    "What skills gaps exist in the organization?",
    "How can I optimize team performance?"
]

DELEGATOR_QUESTIONS = [
    "How many tasks can I assign today?",
    "Who completes tasks without multiple instructions?",
    "Which team members need detailed guidance?",
    "Who goes beyond basic task requirements?",
    "Who provides regular progress updates?",
    "Which employees are poor communicators?",
    "Who adapts quickly to new tasks?",
    "Which employees need skill development?",
    "Who demonstrates problem-solving abilities?",
    "Who are the best team members for specific tasks?",
    "What's the current workload of my team?",
    "Can I track task progress in real-time?",
    "Who completes tasks fastest in my team?",
    "Which team members need additional support?",
    "What are average completion times for different task types?",
    "How many revisions are typically needed?",
    "Can I see detailed performance metrics?",
    "How can I distribute tasks more effectively?",
    "What are my team's strengths and weaknesses?",
    "Which tasks are most important?"
]

DELEGATEE_QUESTIONS = [
    "What tasks are assigned to me?",
    "How do I mark a task as complete?",
    "How am I performing compared to colleagues?",
    "What's my average task completion time?",
    "How many tasks have I completed this month?",
    "What are my strengths in task handling?",
    "Where can I improve my efficiency?",
    "Can I see my performance history?"
]
